- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)", Installing zinit]
    - [mv ~/.zshrc ~/.zshrc.old || echo "No pre-existing zshrc", Moving old zshrc]
    - description: Installing zoxide and fzf
      command: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          brew install zoxide fzf
        elif command -v pacman &> /dev/null; then
          sudo pacman -S --needed --noconfirm zoxide fzf
        fi

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vimrc:
    ~/.tmux.conf:
    ~/.scripts:
    ~/.config/nnn:
    ~/.config/nvim:
    ~/.config/zathura:
    ~/.aerospace.toml:
    ~/.config/atuin/config.toml: atuin-config.toml
    ~/.claude/CLAUDE.md: .claude/CLAUDE.md
    ~/.claude/statusline-command.sh: .claude/statusline-command.sh
    ~/.config/zed/settings.json: zed/settings.json
    ~/.config/ghostty:

- create:
    - ~/downloads
    - ~/code
    - ~/.cache/zsh
    - ~/.local/share/pnpm

