- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./idempotent-clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim, Installing packer.nvim]
    - [./idempotent-clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting, Installing zsh-syntax-highlighting]
    - [./idempotent-clone https://github.com/reobin/typewritten.git $HOME/.oh-my-zsh/custom/themes/typewritten, Installing typewritten theme]
    - [mv ~/.zshrc ~/.zshrc.old || echo "No pre-existing zshrc", Moving old zshrc]

# Tricky to get right in dotbot, so just leaving this as a command to paste in on new machines
# sh -c $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)  --unattended --keep-zshrc

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vimrc:
    ~/.tmux.conf:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/i3:
    ~/.config/i3blocks:
    ~/.config/nnn:
    ~/.config/nvim:
    ~/.config/picom.conf:
    ~/.config/rofi:
    ~/.config/sway:
    ~/.config/zathura:
    ~/.config/yabai:
    ~/.config/skhd:
    ~/.xinitrc:
    ~/.Xresources:

- create:
    - ~/downloads
    - ~/code
    - ~/.vim/.undo
    - ~/.vim/.backup
    - ~/.vim/.swp
    - ~/.cache/zsh

