- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.gitconfig:
    ~/.config/alacritty/alacritty.yml:
        force: true



- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [mkdir -p ~/code, Creating code directory]


