- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - ["git submodule update --init --recursive", Installing submodules]

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vim:
    ~/.vimrc:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/i3:
    ~/.config/i3blocks:
    ~/.config/nnn:
    ~/.config/nvim:
    ~/.config/picom.conf:
    ~/.config/rofi:
    ~/.config/sway:
    ~/.config/zathura:
    ~/.xinitrc:

- create:
    - ~/downloads
    - ~/code
    - ~/.vim/.undo
    - ~/.vim/.backup
    - ~/.vim/.swp
    - ~/.cache/zsh

