- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - [git submodule update --init --recursive, Installing submodules]

# Tricky to get right in dotbot, so just leaving these as commands to paste in on new machines
# sh -c $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)  --unattended --keep-zshrc
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
# git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim


- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vim:
    ~/.vimrc:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/i3:
    ~/.config/i3blocks:
    ~/.config/nnn:
    ~/.config/nvim:
    ~/.config/picom.conf:
    ~/.config/rofi:
    ~/.config/sway:
    ~/.config/zathura:
    ~/.xinitrc:

- create:
    - ~/downloads
    - ~/code
    - ~/.vim/.undo
    - ~/.vim/.backup
    - ~/.vim/.swp
    - ~/.cache/zsh

