- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./idempotent-clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim, Installing packer.nvim]
    - [bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)", Installing zinit]
    - [mv ~/.zshrc ~/.zshrc.old || echo "No pre-existing zshrc", Moving old zshrc]

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vimrc:
    ~/.tmux.conf:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/nnn:
    ~/.config/nvim:
    ~/.config/zathura:
    ~/.aerospace.toml:
    ~/.config/atuin/config.toml: atuin-config.toml
    ~/.claude/CLAUDE.md: .claude/CLAUDE.md
    ~/.claude/statusline-command.sh: .claude/statusline-command.sh
    ~/.config/zed/settings.json: zed/settings.json

- create:
    - ~/downloads
    - ~/code
    - ~/.cache/zsh

