- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc, Installing oh-my-zsh]
    - [git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting", Installing zsh-syntax-highlighting]

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vim:
    ~/.vimrc:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/sway:
    ~/.config/i3:
    ~/.config/i3blocks:
    ~/.config/picom.conf:
    ~/.config/rofi:
    ~/.config/nnn:
    ~/.config/zathura:
    ~/.xinitrc:

- create:
    - ~/downloads
    - ~/code
    - ~/.vim/.undo
    - ~/.vim/.backup
    - ~/.vim/.swp
    - ~/.cache/zsh

