- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.zshrc:
    ~/.zprofile:
    ~/.vim:
    ~/.vimrc:
    ~/.scripts:
    ~/.config/alacritty:
    ~/.config/sway:
    ~/.config/rofi:
    ~/.config/nnn:
    ~/.config/zathura:
    ~/.xinitrc:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [mkdir -p ~/code, Creating code directory]
  - [mkdir -p ~/.vim/.undo ~/.vim/.backup ~/.vim/.swp, Creating vim directories]

