#!/bin/bash

# Simple stopwatch script for timing Rubik's cube runs.

date1=`date +%s`; while true; do 
   echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r" | figlet;
   sleep 0.1;
   clear;
done

